### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by 202122209010** [zezhishao/STID#1]
Hi：
         I tried to run your code, but I didn't run through
         TypeError: forward() missing 4 required positional arguments: 'future_data', 'batch_seen', 'epoch', and 'train'
         Thanks so much for your reply.

**Comment by zezhishao** [comment]
Thanks for your comments.
The bug has been fixed in the commit [fix: 🐛 remove unused parameters in STID_arch.py.](https://github.com/zezhishao/STID/commit/a2883025c0f47f6b4ab6236f26e8869e4a0c2255).
