### ISSUE TITLE
关于模型维度的处理

### ISSUE THREAD

**Issue by kpmokpmo** [zezhishao/STID#3]
您好，模型开始前的代码是这样的，备注是我自己写的维度：
batch_size, _, num_nodes, _ = input_data.shape  # B,L,N,C
input_data = input_data.transpose(1, 2).contiguous()  # B,N,L,C
input_data = input_data.view(batch_size, num_nodes, -1).transpose(1, 2).unsqueeze(-1)  # B,N,(LC)->B,(LC),N->B,(LC),N,1
time_series_emb = self.time_series_emb_layer(input_data)
如果我没理解错的话L是窗口长度，C是每个节点的dim，请问这里为什么把L，C合并了，而不是把NC合并呢？谢谢

**Comment by zezhishao** [comment]
为什么是合并NC呢？

**Comment by kpmokpmo** [comment]
> 为什么是合并NC呢？

额也许是我对情景理解的不对。我以为N和C基本是同质的，都是channel或feature。比如有N个电表，每个电表有C个字段这样的，所以认为NC应该合并。很多时序问题直接设定的时候就是B,C,L，没有第四个维度。

**Comment by zezhishao** [comment]
STID主要关注多元时序，N这个维度需要保留以添加Spatial Identity。

**Comment by kpmokpmo** [comment]
space embedding本来也是（N,hidden_dim），和(N,C）是类似的吧，都是特征维度的。L应该是length即窗口长度吧，LC合并了，窗口长度变C倍有点诡异。我以为BLNC是指batch,length,node,channel per node的意思。。

**Comment by zezhishao** [comment]
LC合并到一起并不是为了增大时间窗口。
LC合并到一起，是因为STID只用了一个全连接层做了Encoding，投射到d维度。
同样，你也可以使用任意的其他网络，比如RNN/TCN把Channel数为N的点投射成d维度。

**Comment by zezhishao** [comment]
LC合并到一起并不是为了增大时间窗口。

LC合并到一起，是因为STID只用了一个全连接层做了Encoding，投射到d维度。直接合并LC方便全连接层做计算。

同样，你也可以使用任意的其他网络，比如RNN/TCN把Channel数为N的点投射成d维度。这时候你就不能LC合并了。

**Comment by kpmokpmo** [comment]
嗯嗯，明白了，感谢指点：）
