### ISSUE TITLE
The time series embedding in file "stid_arch.py"

### ISSUE THREAD

**Issue by STEVEN-PP** [zezhishao/STID#5]
```
# prepare data
input_data = history_data[..., range(self.input_dim)]
...
# time series embedding
batch_size, _, num_nodes, _ = input_data.shape
input_data = input_data.transpose(1, 2).contiguous()
input_data = input_data.view(batch_size, num_nodes, -1).transpose(1, 2).unsqueeze(-1)
time_series_emb = self.time_series_emb_layer(input_data)
```
I want to know whether the shape of "input_data" in `input_data = input_data.transpose(1, 2).contiguous()`  should be (B,N,L,1). But now it is (B,N,L,3). And i think the code `input_data = history_data[..., range(self.input_dim)]` should be replaced with `input_data = history_data[..., 0]`.

**Comment by zezhishao** [comment]
Either way works, and adding temporal features will slightly increase performance.

**Comment by STEVEN-PP** [comment]
Clear! Thanks!
