### ISSUE TITLE
关于Spatial and Temporal Identities的问题

### ISSUE THREAD

**Issue by Waterkin** [zezhishao/STID#8]
您好！看到您的论文，感觉大道之简，但本人不太熟悉时空预测领域问题，想请教一下：

为什么要将时间信息和空间信息作为embedding去学，而不直接将时间信息和空间信息作为特征输入呢？是因为该领域的数据集没有时间信息和空间信息么，如果是这样，方便问下该领域数据集的输入特征是什么吗？

**Comment by zezhishao** [comment]
感谢您的关注！时间和空间信息作为embedding去自适应地学习是更加合理的做法。

数据集本身并不提供时间和空间的Attributes。
虽然我们可以通过一些特殊方法（例如空间维度上使用Node2Vec，时间维度上使用one-hot编码）来产生特征，但我们并不能确保这样的特征是不是合适的。
例如，空间维度的embedding之间的相似度，通常代表着时间序列之间的相似度。而通过特殊方法产生的结果不一定是最优的。
从效果来看不如让模型自适应的去学习时间和空间的embedding。

模型的输入数据是一个`[B, L, N, C]`的Tensor，其中`B=batch size`, `L=sequence length`, `N=number of variates`, `C=features of each variate at each time step`。
`C`的第一维通常是传感器测量出来的值，例如Traffic Speed, Traffic Flow。后续的维度通常是Temporal Features。例如第二维是Time in Day，第三维是Day in Week，后续类推。
更详细的数据预处理可以参考：[这一行](https://github.com/zezhishao/BasicTS/blob/b10534a81f8fc11c65f3103abafc5533f306ef0e/scripts/data_preparation/METR-LA/generate_training_data.py#L68) ~ [这一行](https://github.com/zezhishao/BasicTS/blob/b10534a81f8fc11c65f3103abafc5533f306ef0e/scripts/data_preparation/METR-LA/generate_training_data.py#L94)。

**Comment by Waterkin** [comment]
感谢您详尽的回复，完美解答了我的疑惑！非常solid的工作，follow学习一下~
